version: 2.1

orbs:
  node: circleci/node@5

jobs:

  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."
  
  installing_dependencies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies..."
    
  code_analysis:
    executor: node/default
    steps:
      - checkout
      - run: echo "Analysating the code...."

  cleaning_and_Packaging:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning everything and packaging the project...."

  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/

  integration_testing: 
    executor: node/default
    steps:
      - checkout
      - run: echo "Testing integrations...."

  regression_testing:
    executor: node/default
    steps:
      - checkout
      - run: echo "Testing regressions..."

  performance_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing performence...."

  security_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing security...."

  compatibility_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing the compatibility of the code...."

  accessibility_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing the accessibility of the code...."

  # Section DEPLOY

  deploy_feature:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to feature environment..."

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

workflows:
  version: 2
  build-test-deploy:

    jobs:

      - build

      # Tous les tests de premier niveau qui regardent si le build est bien fait avant de commencer à tester.
      - installing_dependencies:
          requires:
            - build

      - code_analysis:
          requires:
            - build

      - unit_tests:
          requires:
            - build

      - cleaning_and_Packaging:
          requires:
            - build

    
      - regression_testing:
          requires:
            - build

    # Tests de dernier niveau qui demande la réussite d'un tâche auparavent en fonction du test effectué.

      - integration_testing:  # Vu que ce test est demandé seulement pour déployer sur le main je l'exclue des autres branches.
          requires:
            - Regression_testing
          filters:
            branches:
              only:
                - main

      - performance_testing:
          requires:
            - code_analysis
            
      - security_testing:
          requires:
            - unit_tests

      - compatibility_testing:
          requires:
            - installing_dependencies

      - accessibility_testing:
          requires:
            - cleaning_and_Packaging

    # Section DEPLOY

      # Pour le déploiement sur la branche feature j'y ai mis que le stricte minimum pour permettre aux développeurs de pouvoir tester leur code sans trop de contraintes.
      - deploy_feature:
          requires:
            - regression_testing
            - performance_testing
          filters:
            branches:
              only:
                - feature

      # Une grande majorité des tests sont là sauf celui de l'intégration qui est réservé pour le déploiement sur la branche main.
      - deploy_dev:
          requires:
            - regression_testing
            - performance_testing
            - compatibility_testing
            - accessibility_testing
          filters:
            branches:
              only:
                - develop

      # Tous les tests de dernier niveau y sont.
      - deploy_prod:
          requires:
            - performance_testing
            - compatibility_testing
            - security_testing
            - integration_testing
            - accessibility_testing
          filters:
            branches:
              only:
                - main
