version: 2.1

orbs:
  node: circleci/node@5

jobs:
  
  # Section BUILD
  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building things..."
  
  Installing_dependencies:
    executor: node/default
    steps:
      - checkout
      - run: echo "Installing dependencies..."
    
  Code_analysis:
    executor: node/default
    steps:
      - checkout
      - run: echo "Analysating the code...."

  Cleaning_and_Packaging:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning everything and packaging the project...."

  # Section TESTS
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/

  Integration_testing: 
    executor: node/default
    steps:
      - checkout
      - run: echo "Testing integrations...."

  Regression_testing:
    executor: node/default
    steps:
      - checkout
      - run: echo "Testing regressions..."

  Performance_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing performence...."

  Security_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing security...."

  Compatibility_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing the compatibility of the code...."

  Accessibility_testing:
    executor: node/default
    steps: 
      - checkout
      - run: echo "Testing the accessibility of the code...."

  # Section DEPLOY

  deploy_feature:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to feature environment..."

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

workflows:
  version: 2
 # Deployment part
  build-test-deploy:

    jobs:
    # Section BUILD
      - build
      - Installing_dependencies:
          requires:
            - build

      - Code_analysis:
          requires:
            - build

    # Section TESTS
      - unit_tests:
          requires:
            - build

      - Regression_testing:
          requires:
            - build

      - Integration_testing:
          requires:
            - unit_tests
            - Regression_testing
            - Installing_dependencies

      - Performance_testing:
          requires:
            - Code_analysis
            - Regression_testing
            
      - Security_testing:
          requires:
            - unit_tests

      - Compatibility_testing:
          requires:
            - Installing_dependencies

    # Section DEPLOY
      - deploy_feature:
          requires:
            - unit_tests
            - Regression_testing
          filters:
            branches:
              only:
                - feature

      - deploy_dev:
          requires:
            - build
            - unit_tests
            - Regression_testing
            - Performance_testing
            - Compatibility_testing
          filters:
            branches:
              only:
                - develop

      - deploy_prod:
          requires:
            - Performance_testing
            - Compatibility_testing
            - Security_testing
          filters:
            branches:
              only:
                - main
